version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: alx_property_postgres
    environment:
      POSTGRES_DB: property_listings_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - property_network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: alx_property_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - property_network
    restart: unless-stopped

  web:
    build: .
    container_name: alx_property_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - property_network
    environment:
      - DEBUG=1
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  property_network:
    driver: bridge
